
% check if the PIQI environment variable is defined; when defined it points to
% the "piqi" binary executable
%
% also, see ./get-piqi-binary
case {os:find_executable("piqi"), os:getenv("PIQI")} of
    {false, false} ->
        % keep the original config including the piqi_binary dependency
        CONFIG;
    _ ->
        % remove the deps section that includes the piqi_binary dependency
        lists:keydelete(deps, 1, CONFIG)
end.

% ex: ft=erlang
