
% check if the PIQI environment variable is defined; when defined it points to
% the "piqi" binary executable
%
% also, see ./get-piqi-binary
case os:getenv("PIQI") of
    false ->
        % keep the original config including the piqi_binary dependency
        CONFIG;
    PiqiPath ->
        % remove the deps section that includes the piqi_binary dependency
        lists:keydelete(deps, 1, CONFIG)
end.


% ex: ft=erlang
