
PIQI ?= ../../priv/bin/piqi

PIQIC = ../../priv/bin/piqic-erlang
PIQIC_FLAGS ?= #--trace


# strip ".proto" suffix in ".proto.piqi" file extension
PIQI_NOPROTO_FILES = $(PIQI_FILES:%.proto.piqi=%.piqi)

PIQI_ERL_FILES = $(PIQI_NOPROTO_FILES:%.piqi=%_piqi.erl)
PIQI_HRL_FILES = $(PIQI_NOPROTO_FILES:%.piqi=%_piqi.hrl)

PIQI_ERLANG_FILES = $(PIQI_ERL_FILES) $(PIQI_HRL_FILES)


$(PIQI_ERLANG_FILES): $(PIQI_FILES) $(PIQIC)
	set -e; \
	for i in $(PIQI_FILES); do \
		$(PIQIC) $(PIQIC_FLAGS) $$i; \
	done


clean::
	rm -f $(PIQI_ERLANG_FILES)


# ex: ft=make
