#!/bin/sh

if [ $# -gt 2 ]
then
    echo "Usage: $0 [<number of parallel clients>] [<number of test runs>]"
    exit 1
fi


#BOOT="-boot start_sasl"
RUN="test main $1 $2"
ERL_PATH="-pa ../piqi/ebin"


erl $ERL_PATH -noshell $BOOT -s piqi start -run $RUN -s erlang halt
#rlwrap erl -oldshell $ERL_PATH -s piqi start -run $RUN #-s erlang halt

