#!/bin/sh

if [ $# -gt 2 ]
then
    echo "Usage: $0 [<number of parallel clients>] [<number of test runs>]"
    exit 1
fi


#BOOT="-boot start_sasl"
export ERL_LIBS=../lib:../../_build/default/lib/


RUN="test main $1 $2"
erl -noshell $BOOT -s piqi start -run $RUN -s erlang halt
#rlwrap erl -oldshell -s piqi start -run $RUN #-s erlang halt

