
PIQIC = $(REBAR_DEPS_DIR)/piqi/priv/bin/piqic-erlang
PIQIC_FLAGS = #--trace


PIQI_FILES = addressbook.proto.piqi

PIQI_ERL_FILES = $(PIQI_FILES:%.proto.piqi=%_piqi.erl)
PIQI_HRL_FILES = $(PIQI_FILES:%.proto.piqi=%_piqi.hrl)

PIQI_ERLANG_FILES = $(PIQI_ERL_FILES) $(PIQI_HRL_FILES)


all: $(PIQI_ERLANG_FILES)


$(PIQI_ERLANG_FILES): $(PIQI_FILES)
	set -e; \
	for i in $^; do \
		$(PIQIC) $(PIQIC_FLAGS) $$i; \
	done


clean:
	rm -f $(PIQI_ERLANG_FILES)


# ex: ft=make
