#!/bin/sh

set -ex


export ERL_LIBS="../lib:../../_build/default/lib"
export ERL_FLAGS="-pa ebin -pa _build/default/lib/untyped_json_xml/ebin"

erl -noshell -s piqi start -run test run person.piq -s erlang halt
erl -noshell -s piqi start -run test run person-xml.piq -s erlang halt
erl -s piqi start < test.escript

