#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: $0 ADDRESS_BOOK_FILE"
    exit 1
fi


ERL_FLAGS="-pa ../../ebin -pa ../../_build/default/lib/piqi/ebin"
ERL_FLAGS="$ERL_FLAGS -pa ebin -pa _build/default/lib/addressbook/ebin"
export ERL_FLAGS

RUN="add_person run"

erl -noshell -run $RUN "$0" "$1" -s erlang halt
