#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: $0 ADDRESS_BOOK_FILE"
    exit 1
fi


ERL_FLAGS="-pa ../../ebin -pa ../../_build/default/lib/piqi/ebin"
ERL_FLAGS="$ERL_FLAGS -pa ebin -pa _build/default/lib/addressbook/ebin"
export ERL_FLAGS

RUN="io_json_xml_pb run"

erl -noshell -s piqi start -run $RUN "$1" -s erlang halt
