#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: $0 ADDRESS_BOOK_FILE"
    exit 1
fi


export ERL_LIBS="../lib:../../_build/default/lib"
export ERL_FLAGS="-pa ebin -pa _build/default/lib/addressbook/ebin"

RUN="list_people run"

erl -noshell -run $RUN "$1" -s erlang halt
