#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: $0 ADDRESS_BOOK_FILE"
    exit 1
fi


RUN="list_people run"
ERL_PATH="-pa ebin -pa deps/piqi/ebin"


erl $ERL_PATH -noshell -run $RUN "$1" -s erlang halt

