#!/bin/sh
#
# copies pre-built piqi binary from the piqi_binary rebar dependency to
# ./priv/piqi-binary/$os_version
#
# alternatively, when $PIQI environment variable is defined, it is used as
# source path for copying piqi binary

set -e


os_version=`uname -s`-`uname -m`
piqi_dir="priv/piqi-binary/$os_version"


# check if the PIQI environment variable is defined; when defined it points to
# the "piqi" binary executable
if [ -n "$PIQI" ]
then
	dst=$piqi_dir/piqi
	if [ ! -f $dst ] || [ "$PIQI" -nt $dst ]
	then
		mkdir -p $piqi_dir
		cp -a "$PIQI" $dst
	fi
else
	PIQI=$piqi_dir/piqi

	if [ ! -e $PIQI ]
	then
	    mkdir -p $piqi_dir
	    cp -a $REBAR_DEPS_DIR/piqi_binary/$os_version/piqi $PIQI
	fi

	test -e $PIQI
fi
