#!/bin/sh

set -e
#set -x


if [ -n "$REBAR_DEPS_DIR" ]
then
        true
elif [ -d deps ]
then
        REBAR_DEPS_DIR=deps
elif [ -d ../../deps ]
then
        REBAR_DEPS_DIR=../../deps
else
        echo "can't find rebar 'deps' directory around `pwd`" 1>&2
        exit 1
fi

export REBAR_DEPS_DIR


rm -f src
ln -sf "$REBAR_DEPS_DIR/piqi_src/piqi-erlang/src"

rm -f include
ln -sf "$REBAR_DEPS_DIR/piqi_src/piqi-erlang/include"

